/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    medios: Medio;
    paquetes: Paquete;
    casas: Casa;
    ordenes: Ordene;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    medios: MediosSelect<false> | MediosSelect<true>;
    paquetes: PaquetesSelect<false> | PaquetesSelect<true>;
    casas: CasasSelect<false> | CasasSelect<true>;
    ordenes: OrdenesSelect<false> | OrdenesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios".
 */
export interface Medio {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    tarjeta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    pantalla?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paquetes".
 */
export interface Paquete {
  id: number;
  nota?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Completa la pauta de renders: llegada al atardecer, terraza, estar, cocina, dormitorio y nocturna.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casas".
 */
export interface Casa {
  id: number;
  nombre: string;
  numero: string;
  slug?: string | null;
  ubicacion?: string | null;
  publicada?: boolean | null;
  specs: {
    superficie: number;
    pisos: number;
    dormitorios: number;
    banos: number;
  };
  precio: number;
  precioOferta?: number | null;
  precioAjustes?: number | null;
  coordenadas?: {
    lat?: number | null;
    lng?: number | null;
  };
  momentos?: {
    llegada?: {
      imagen?: (number | null) | Medio;
      relato?: string | null;
    };
    visita?:
      | {
          imagen: number | Medio;
          titulo: string;
          frase: string;
          puntoX: number;
          puntoY: number;
          id?: string | null;
        }[]
      | null;
    plano?: {
      /**
       * Formato: [{"de":[x,y],"a":[x,y],"grosor":3}] en metros desde la esquina superior izquierda.
       */
      muros?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      recintos?:
        | {
            nombre: string;
            superficie: number;
            poligono:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            render?: (number | null) | Medio;
            frase?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    maqueta?: {
      glb?: (number | null) | Medio;
    };
    fotosObra?:
      | {
          imagen: number | Medio;
          lugar?: string | null;
          /**
           * Ejemplo: 13.02.2023
           */
          fecha?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  materiales?:
    | {
        nombre: string;
        frase: string;
        imagen?: (number | null) | Medio;
        id?: string | null;
      }[]
    | null;
  paquete?: {
    zip?: (number | null) | Paquete;
    laminas?: number | null;
    incluyeDwg?: boolean | null;
    incluyeEett?: boolean | null;
  };
  faq?:
    | {
        pregunta: string;
        respuesta: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ordenes".
 */
export interface Ordene {
  id: number;
  email: string;
  casa: number | Casa;
  monto: number;
  conAjustes?: boolean | null;
  descripcionAjustes?: string | null;
  estado: 'pendiente' | 'pagada' | 'fallida';
  mpPreferenceId?: string | null;
  mpPaymentId?: string | null;
  tokenDescarga?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'medios';
        value: number | Medio;
      } | null)
    | ({
        relationTo: 'paquetes';
        value: number | Paquete;
      } | null)
    | ({
        relationTo: 'casas';
        value: number | Casa;
      } | null)
    | ({
        relationTo: 'ordenes';
        value: number | Ordene;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios_select".
 */
export interface MediosSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        tarjeta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        pantalla?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paquetes_select".
 */
export interface PaquetesSelect<T extends boolean = true> {
  nota?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casas_select".
 */
export interface CasasSelect<T extends boolean = true> {
  nombre?: T;
  numero?: T;
  slug?: T;
  ubicacion?: T;
  publicada?: T;
  specs?:
    | T
    | {
        superficie?: T;
        pisos?: T;
        dormitorios?: T;
        banos?: T;
      };
  precio?: T;
  precioOferta?: T;
  precioAjustes?: T;
  coordenadas?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  momentos?:
    | T
    | {
        llegada?:
          | T
          | {
              imagen?: T;
              relato?: T;
            };
        visita?:
          | T
          | {
              imagen?: T;
              titulo?: T;
              frase?: T;
              puntoX?: T;
              puntoY?: T;
              id?: T;
            };
        plano?:
          | T
          | {
              muros?: T;
              recintos?:
                | T
                | {
                    nombre?: T;
                    superficie?: T;
                    poligono?: T;
                    render?: T;
                    frase?: T;
                    id?: T;
                  };
            };
        maqueta?:
          | T
          | {
              glb?: T;
            };
        fotosObra?:
          | T
          | {
              imagen?: T;
              lugar?: T;
              fecha?: T;
              id?: T;
            };
      };
  materiales?:
    | T
    | {
        nombre?: T;
        frase?: T;
        imagen?: T;
        id?: T;
      };
  paquete?:
    | T
    | {
        zip?: T;
        laminas?: T;
        incluyeDwg?: T;
        incluyeEett?: T;
      };
  faq?:
    | T
    | {
        pregunta?: T;
        respuesta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ordenes_select".
 */
export interface OrdenesSelect<T extends boolean = true> {
  email?: T;
  casa?: T;
  monto?: T;
  conAjustes?: T;
  descripcionAjustes?: T;
  estado?: T;
  mpPreferenceId?: T;
  mpPaymentId?: T;
  tokenDescarga?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}